#!/usr/bin/env python3
"""
Generate the FPC resource script + index unit that embed the static asset trees into the
wekan-lite binary, for the single-binary (-dWLEMBED) build. See docs/static.md.

Two trees are embedded by default (run from the repo root):
    public   -> served at '/'      (key prefix '')        e.g. js/interact.js
    i18n     -> served at '/i18n'   (key prefix 'i18n/')   e.g. i18n/data/en.jsn
The embedded lookup is keyed by the full URL-relative path (prefix + path within the tree),
matching wlstatic.ServeStatic.

Usage:
    python3 releases/genasset.py [out_pas] [out_rc] [root[:url_prefix] ...]
        out_pas     default: src/wlassets.pas
        out_rc      default: src/wlpublic.rc
        root specs  default: public  i18n:i18n
                    each is DIR or DIR:URL_PREFIX (prefix '' means served at the root)

RCDATA paths in the .rc are written relative to the .rc file's directory, so the embed build
runs from src/ regardless of where genasset.py is invoked:
    python3 releases/genasset.py                       # writes src/wlassets.pas + src/wlpublic.rc
    cd src && fpcres wlpublic.rc -o wlpublic.res -of res
    fpc -dWLEMBED -O3 -Xs -o ../welite wlhttp.lpr

The generated wlassets unit reads each file back via TResourceStream and registers
wlstatic.EmbeddedLookup, so ServeStatic serves from the executable with nothing on disk.
"""
import os
import sys

DEFAULT_ROOTS = ["public", "i18n:i18n"]


def pas_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def parse_root(spec: str):
    # DIR or DIR:URL_PREFIX  (prefix defaults to the dir's basename-less '' for served-at-root)
    if ":" in spec:
        d, prefix = spec.split(":", 1)
    else:
        d, prefix = spec, ""
    key_prefix = (prefix.strip("/") + "/") if prefix.strip("/") else ""
    return d, key_prefix


def main() -> int:
    args = sys.argv[1:]
    out_pas = args[0] if len(args) > 0 else os.path.join("src", "wlassets.pas")
    out_rc = args[1] if len(args) > 1 else os.path.join("src", "wlpublic.rc")
    roots = args[2:] if len(args) > 2 else DEFAULT_ROOTS

    rc_dir = os.path.dirname(os.path.abspath(out_rc)) or "."

    # (url_key, rcdata_path) for every file across every root
    entries = []
    for spec in roots:
        d, key_prefix = parse_root(spec)
        if not os.path.isdir(d):
            print(f"genasset: no such directory: {d}", file=sys.stderr)
            return 1
        for root, _, names in os.walk(d):
            for n in names:
                full = os.path.join(root, n)
                rel = os.path.relpath(full, d).replace(os.sep, "/")
                url_key = key_prefix + rel
                rc_path = os.path.relpath(os.path.abspath(full), rc_dir).replace(os.sep, "/")
                entries.append((url_key, rc_path))
    entries.sort()
    n = len(entries)

    # resource script: numeric id -> file path (relative to where fpcres runs, i.e. rc_dir)
    with open(out_rc, "w", encoding="utf-8") as f:
        for i, (_url, rc_path) in enumerate(entries, start=1):
            f.write(f'{i} RCDATA "{rc_path}"\n')

    # index unit: url key (full URL-relative path) -> resource id; reads via TResourceStream
    with open(out_pas, "w", encoding="utf-8") as f:
        f.write("unit wlassets;\n")
        f.write("{ GENERATED by releases/genasset.py - do not edit. Embeds the asset trees via FPC resources. }\n")
        f.write("{$mode objfpc}{$H+}\n\ninterface\n\nimplementation\n\n")
        f.write("uses SysUtils, Classes, wlstatic;\n\n")
        f.write("{$R wlpublic.res}\n\n")
        f.write(f"const AC = {n};\n")
        if n:
            f.write("  Urls: array[0..AC-1] of string = (\n")
            f.write(",\n".join("    " + pas_str(url) for url, _ in entries))
            f.write(");\n")
            f.write("  Ids: array[0..AC-1] of Integer = (\n")
            f.write(",\n".join("    " + str(i) for i in range(1, n + 1)))
            f.write(");\n")
        f.write("""
function Lookup(const Rel: string; out Data: TBytes; out Mime: string): Boolean;
var i: Integer; rs: TResourceStream;
begin
  Result := False; Mime := ''; SetLength(Data, 0);
  for i := 0 to AC - 1 do
    if Urls[i] = Rel then
    begin
      rs := TResourceStream.CreateFromID(HINSTANCE, Ids[i], RT_RCDATA);
      try
        SetLength(Data, rs.Size);
        if rs.Size > 0 then rs.ReadBuffer(Data[0], rs.Size);
      finally
        rs.Free;
      end;
      Exit(True);
    end;
end;

initialization
  wlstatic.EmbeddedLookup := @Lookup;
end.
""")
    print(f"genasset: wrote {out_pas} and {out_rc} ({n} assets from {', '.join(roots)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
