#!/usr/bin/env python3
"""
Generate the FPC resource script + index unit that embed public/ into the wekan-lite binary,
for the single-binary (-dWLEMBED) build. See docs/static-assets.md.

Usage:
    python3 tools/genassets.py [public_dir] [out_pas] [out_rc]
        public_dir  default: public
        out_pas     default: wlassets.pas
        out_rc      default: wlpublic.rc

Then (from the freepascal/ dir):
    fpcres wlpublic.rc -o wlpublic.res -of res
    fpc -dWLEMBED -O3 -Xs -o wekanlite wlhttp.lpr

The generated wlassets unit reads each file back via TResourceStream and registers
wlstatic.EmbeddedLookup, so ServeStatic serves from the executable with nothing on disk.
"""
import os
import sys


def pas_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> int:
    pub = sys.argv[1] if len(sys.argv) > 1 else "public"
    out_pas = sys.argv[2] if len(sys.argv) > 2 else "wlassets.pas"
    out_rc = sys.argv[3] if len(sys.argv) > 3 else "wlpublic.rc"

    if not os.path.isdir(pub):
        print(f"genassets: no such directory: {pub}", file=sys.stderr)
        return 1

    files = []
    for root, _, names in os.walk(pub):
        for n in names:
            full = os.path.join(root, n).replace(os.sep, "/")
            rel = os.path.relpath(full, pub).replace(os.sep, "/")
            files.append((rel, full))
    files.sort()
    n = len(files)

    # resource script: numeric id -> file path (relative to where fpcres runs)
    with open(out_rc, "w", encoding="utf-8") as f:
        for i, (_rel, full) in enumerate(files, start=1):
            f.write(f'{i} RCDATA "{full}"\n')

    # index unit: url (rel path, forward slashes) -> resource id; reads via TResourceStream
    with open(out_pas, "w", encoding="utf-8") as f:
        f.write("unit wlassets;\n")
        f.write("{ GENERATED by tools/genassets.py - do not edit. Embeds public/ via FPC resources. }\n")
        f.write("{$mode objfpc}{$H+}\n\ninterface\n\nimplementation\n\n")
        f.write("uses SysUtils, Classes, wlstatic;\n\n")
        f.write("{$R wlpublic.res}\n\n")
        f.write(f"const AC = {n};\n")
        if n:
            f.write("  Urls: array[0..AC-1] of string = (\n")
            f.write(",\n".join("    " + pas_str(rel) for rel, _ in files))
            f.write(");\n")
            f.write("  Ids: array[0..AC-1] of Integer = (\n")
            f.write(",\n".join("    " + str(i) for i in range(1, n + 1)))
            f.write(");\n")
        f.write("""
function Lookup(const Rel: string; out Data: TBytes; out Mime: string): Boolean;
var i: Integer; rs: TResourceStream;
begin
  Result := False; Mime := ''; SetLength(Data, 0);
  for i := 0 to AC - 1 do
    if Urls[i] = Rel then
    begin
      rs := TResourceStream.CreateFromID(HINSTANCE, Ids[i], RT_RCDATA);
      try
        SetLength(Data, rs.Size);
        if rs.Size > 0 then rs.ReadBuffer(Data[0], rs.Size);
      finally
        rs.Free;
      end;
      Exit(True);
    end;
end;

initialization
  wlstatic.EmbeddedLookup := @Lookup;
end.
""")
    print(f"genassets: wrote {out_pas} and {out_rc} ({n} assets from {pub}/)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
